name: BSE Award Watch

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 3-9 * * 1-5"

concurrency:
  group: bse-award-watch
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  collect-awards:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Kolkata
      MINUTES_FROM_OPEN: 0
      MINUTES_TO_CLOSE: 0
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Compile scripts
        run: npm run build

      - name: Guard trading window
        id: guard
        run: npm run guard

      - name: Fetch BSE awards
        run: npm run fetch

      - name: Merge intraday state
        run: npm run merge

      - name: Render README snapshot
        run: npm run render

      - name: Detect repository changes
        id: changes
        run: |
          if git status --porcelain | grep . >/dev/null; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit intraday snapshot
        env:
          GIT_AUTHOR_NAME: Yash Karanke
          GIT_AUTHOR_EMAIL: dex.papa@gmail.com
          GIT_COMMITTER_NAME: Yash Karanke
          GIT_COMMITTER_EMAIL: dex.papa@gmail.com
          PAT_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          if [ -z "$PAT_TOKEN" ]; then
            echo "BOT_PAT secret is required to push changes."
            exit 1
          fi
          git add README.md data
          git commit -m "chore: refresh BSE award snapshot"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}

      - name: Upload data artefacts
       
        uses: actions/upload-artifact@v4
        with:
          name: bse-awards-${{ github.run_id }}
          path: data
